### ISSUE TITLE
Worker log switch

### ISSUE THREAD

**Issue by wilkek** [infretis/infretis#118]
[restart06.log](https://github.com/user-attachments/files/17602664/restart06.log)
[worker16.log](https://github.com/user-attachments/files/17602665/worker16.log)
[worker24.log](https://github.com/user-attachments/files/17602666/worker24.log)
 tried to upgrade the ams branch to the latest infRETIS and we see that workers in the logs are changing. You fixed that issue previously. Do you remember how you did that? We currently get the problem, that amsworkers get the same state names:
In this case it is: 

 039_44_conf.rkf
The problem is, that the 44 is a number that is increasing every new shooting. The problem is, that the 44 is connected to the workerX.log-file and that is not locked to the infretis worker. I attached the two log files where 039_44_conf.rkf appears. So two different states are named the same. If you have an idea how to fix this or if it is an asyncio error, that Lucas needs to tackle, I would be happy to know. 

Best, Konrad 

example:
worker16.log:
---------------------------------------------------------------------------------------------
[INFO]: AMS setting output file: /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker12/011_42_trajB.rkf
.....
[INFO]:AMS setting output file: /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker12/011_43_trajF.rkf
....
[INFO]: AMS reversing velocities for /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker23/039_44_conf.rkf
---------------------------------------------------------------------------------------------

worker24.log:
---------------------------------------------------------------------------------------------
[INFO]: AMS setting output file: /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker23/039_42_trajB.rkf
.....
[INFO]: AMS setting output file: /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker23/039_43_trajF.rkf
.....
[INFO]: AMS Copying snap to snap: /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker23/gen_vel_617961.rkf -> 
      /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker23/039_44_conf.rkf
---------------------------------------------------------------------------------------------

Then crash with error message:

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/konrad/miniforge3/envs/molmod/lib/python3.11/concurrent/futures/process.py", line 256, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konrad/opt/infretis_new/infretis/infretis/core/tis.py", line 93, in run_md
    _, trials, status = select_shoot(picked)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/konrad/opt/infretis_new/infretis/infretis/core/tis.py", line 328, in select_shoot
    accept, new_path, status = sh_moves[move](
                               ^^^^^^^^^^^^^^^
  File "/home/konrad/opt/infretis_new/infretis/infretis/core/tis.py", line 538, in wire_fencing
    success, trial_seg, status = shoot(
                                 ^^^^^^
  File "/home/konrad/opt/infretis_new/infretis/infretis/core/tis.py", line 410, in shoot
    if not shoot_backwards(
           ^^^^^^^^^^^^^^^^
  File "/home/konrad/opt/infretis_new/infretis/infretis/core/tis.py", line 717, in shoot_backwards
    success_back, _ = engine.propagate(
                      ^^^^^^^^^^^^^^^^^
  File "/home/konrad/opt/infretis_new/infretis/infretis/classes/engines/enginebase.py", line 303, in propagate
    initial_file = self.dump_frame(system, deffnm=prefix + "_conf")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konrad/opt/infretis_new/infretis/infretis/classes/engines/enginebase.py", line 231, in dump_frame
    return self.dump_config(system.config, deffnm=deffnm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konrad/opt/infretis_new/infretis/infretis/classes/engines/enginebase.py", line 223, in dump_config
    self._copyfile(pos_file, out_file)
  File "/home/konrad/opt/infretis_new/infretis/infretis/classes/engines/ams_lukas.py", line 647, in _copyfile
    self._copystate(source, dest)
  File "/home/konrad/opt/infretis_new/infretis/infretis/classes/engines/ams_lukas.py", line 616, in _copystate
    self.worker.CopyMDState(source, dest)
  File "/home/konrad/miniforge3/envs/molmod/lib/python3.11/site-packages/scm/plams/interfaces/adfsuite/amsworker.py", line 1073, in CopyMDState
    self._call("CopyMDState", args)
  File "/home/konrad/miniforge3/envs/molmod/lib/python3.11/site-packages/scm/plams/interfaces/adfsuite/amsworker.py", line 1189, in _call
    raise ValueError(ret, args)

**Comment by dz24** [comment]
A simple reason for why this could happen is that the counter() function in `infretis/infretis/classes/engines/enginebase.py` appears to be updated individually on the worker basis, meaning that the same number XX in "_XX_conf.rkf" can appear as many times as there are workers in the system.

A simple fix may be to replace

`        prefix = ens_set["ens_name"] + "_" + str(counter())`

in line `282` in ``infretis/infretis/classes/engines/enginebase.py``

for 

`        prefix = ens_set["ens_name"] + "_" + str(os.getpid()) + "_" + str(counter())`

as seemingly os.getpid() is a number unique to the initiated worker.

**Comment by wilkek** [comment]
That works!

**Comment by wilkek** [comment]
It would still be better to have it fixed as the random number generator is fixed in the same way and starts with the same seed for all workers. I run into this: ValueError: ({'status': 7, 'method': 'CreateMDState', 'argument': 'title', 'message': 'MD state with given title already exists'}, {'title': 'worker15/gen_vel_685089.rkf'})

**Comment by dz24** [comment]
I am not sure which branch you are running on, but it seems that it is the amsworker that creates the digit part of the name and not infretis, on line `506` and `515`, for this branch [https://github.com/wilkek/infretis/blob/3.8/infretis/classes/engines/ams.py#L515](https://github.com/wilkek/infretis/blob/3.8/infretis/classes/engines/ams.py#L515) at least.

I think you can apply the same fix for line `506`.

**Comment by lukasbaldauf** [comment]
Wrote this while debugging, so it's a rather long answer, but it solves the issue when I try to do something similar.

##
To reproduce:

Go to `infretis/examples/ase/H2` and modify the following 3 lines in `infretis0.toml`:

```toml
[infinit]
steps_per_iter = [100]

[runner]
workers = 20
wmdrun = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]
```

In `infrets/classes/engines/ase_engine.py` change `set_mdrun()` by adding the following two lines:

```python
def set_mdrun(self, md_items: dict) -> None:
...
pin = md_items.get("pin", None)
logger.info(f"EXE_DIR: {md_items['exe_dir']} PIN: {pin}")
```

then run 

```bash
inft infinit -toml infretis0.toml
```

Now, if you don't get  KeyError: 'picked' (solved by 595f50b6f4978730a42bb5bf057fa56dad0f4633), the other bug is that in some worker logs, where we expect a certain `PIN`, we may get another workers pin.

### Worker Switchup

It seems that ther worker.log files are switched, so the output of for example worker 23 might suddenly not be in worker23.log anymore, but in some other log file, for example worker16.log.

In worker 16.log we therefore now see the following print:

```textile
[INFO]: self.exe_dir /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/**worker23**
[INFO]: starting wf in 039 with path_n 79941
...
[INFO]: AMS Copying snap to snap: /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker23/gen_vel_110432.rkf -> /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker23/**039_44_conf.rkf**
```

Note that the self.exe_dir is worker23/ and that we generate a new state 039_44_conf.rkf

The move is accepted and we sample the new path. Then, worker23 starts a new move in ensemble 039, the same ensemble as previously. 

In worker24.log we see this:

```textile
[INFO]: self.exe_dir /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/**worker23**
[INFO]: starting wf in 039 with path_n 79945
...
[INFO]: AMS reversing velocities for /mnt/workspace/konrad/Diffusion_CsPbI3/cs_vacancy/infretis/cubic4x4x4/700K/worker23/**039_42_conf.rkf
```

However, for some reason, worker23's counter is now again at 42. It uses the counter of that instance of the module, it seems. The module and the engine are not locked to eachother.

### The Counter

If we give EngineBase a counter, as illustrated below

```python
class EngineBase(metaclass=ABCMeta):
...
    def counter(self):
        """Return how many times this function is called."""
        self.count = 0 if not hasattr(self, "count") else self.count + 1
        return self.count
```

This results in the behaviour that the counter resets every time we get a worker switch in the log file.

If we define the `counter()` method in ase_engine.py, the behavior is the same.

It seems as if the main process doesn't see changes to class instances due to the workers?

In `create_engines()` we add for each engine the line engine.count = 0. This also does not keep it updated.

### A solution in asyncrunner

Lucas noted as a comment in asyncrunner.py on line 159

```python
future = asyncio.run(self._add_work_to_queue(work_unit))
# Need to wait otherwise some race condition can occur
time.sleep(0.05)
```

If we change to `time.sleep(0.5)` stuff is slower but now it works. So it seems as if it is related to the timing.

### Solution

In `as_completed()` in asyncrunner.py, the returned future might not be the actualy future that actually completed first. If we compare all completed future end times and return the one that completed first, it seems to fix the counter issues, and also the workers switching.

**Comment by sroet** [comment]
Just a thing I noticed:
shouldn't 
```python
class EngineBase(metaclass=ABCMeta):
...
    def counter(self):
        """Return how many times this function is called."""
        self.count = 0 if not hasattr(self, "count") else self.count + 1
        return self.count
```
be 
```
class EngineBase(metaclass=ABCMeta):
...
    def counter(self):
        """Return how many times this function is called."""
        self.count = 0 if not hasattr(self, "count") else self.count += 1
        return self.count
```
instead?
